-- No pgAdmin, crie o banco trilha_estrelas e execute este arquivo nele.

CREATE TABLE IF NOT EXISTS perguntas (
  id INTEGER PRIMARY KEY,
  nivel VARCHAR(10) NOT NULL CHECK (nivel IN ('facil', 'medio', 'dificil')),
  pergunta TEXT NOT NULL,
  imagem TEXT NOT NULL,
  opcoes JSONB NOT NULL,
  resposta INTEGER NOT NULL CHECK (resposta >= 0 AND resposta < 4)
);

CREATE TABLE IF NOT EXISTS tentativas (
  id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(18) NOT NULL,
  pergunta_id INTEGER NOT NULL REFERENCES perguntas(id),
  resposta INTEGER NOT NULL CHECK (resposta >= 0 AND resposta < 4),
  correta BOOLEAN NOT NULL,
  respondida_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tentativas DROP CONSTRAINT IF EXISTS tentativas_resposta_check;
ALTER TABLE tentativas ADD CONSTRAINT tentativas_resposta_check CHECK (resposta IS NULL OR (resposta >= 0 AND resposta < 4));

INSERT INTO perguntas (id, nivel, pergunta, imagem, opcoes, resposta) VALUES
(1, 'facil', 'Qual animal faz "miau"?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f431.png', '["Cachorro", "Gato", "Pato", "Cavalo"]', 1),
(2, 'facil', 'Quanto é 2 + 3?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["4", "5", "6", "7"]', 1),
(3, 'facil', 'Qual é a cor do sol?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/2600.png', '["Azul", "Verde", "Amarelo", "Roxo"]', 2),
(4, 'facil', 'Quantas pernas tem uma borboleta?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f98b.png', '["4", "6", "8", "10"]', 1),
(5, 'facil', 'O que usamos para escrever?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/270f.png', '["Lápis", "Sapato", "Prato", "Bola"]', 0),
(6, 'facil', 'Quantos dias tem uma semana?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f4c5.png', '["5", "6", "7", "8"]', 2),
(7, 'facil', 'Qual animal tem uma longa tromba?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f418.png', '["Elefante", "Peixe", "Pinguim", "Rato"]', 0),
(8, 'facil', 'Qual fruta é vermelha e redonda?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f347.png', '["Maçã", "Limão", "Banana", "Melancia"]', 0),
(9, 'facil', 'Qual objeto cortamos papel?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/2702.png', '["Tesoura", "Colher", "Almofada", "Chapéu"]', 0),
(10, 'facil', 'Qual parte do corpo vemos com?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f441.png', '["Ouvidos", "Olhos", "Pés", "Mãos"]', 1),
(11, 'facil', 'Quanto é 5 + 2?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["6", "7", "8", "9"]', 1),
(12, 'facil', 'Qual fruta é amarela e comprida?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f34c.png', '["Banana", "Maçã", "Uva", "Melancia"]', 0),
(13, 'facil', 'Quantos pés tem um cachorro?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f436.png', '["2", "3", "4", "5"]', 2),
(14, 'facil', 'O que sobe quando chove?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f32b.png', '["Neve", "Arco-íris", "Sol", "Lua"]', 1),
(15, 'facil', 'Quanto é 3 + 4?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["6", "7", "8", "9"]', 1),
(16, 'medio', 'Qual fruta é conhecida por ser amarela e comprida?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f34c.png', '["Banana", "Maçã", "Uva", "Melancia"]', 0),
(17, 'medio', 'Qual animal vive na água?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f41f.png', '["Peixe", "Leão", "Coelho", "Galinha"]', 0),
(18, 'medio', 'Qual forma tem três lados?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f53a.png', '["Círculo", "Quadrado", "Triângulo", "Retângulo"]', 2),
(19, 'medio', 'Qual estação é quente?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f308.png', '["Inverno", "Verão", "Outono", "Primavera"]', 1),
(20, 'medio', 'Quantos meses tem um ano?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f5d3.png', '["10", "11", "12", "13"]', 2),
(21, 'medio', 'Qual é o maior animal terrestre?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f418.png', '["Elefante", "Gato", "Macaco", "Cachorro"]', 0),
(22, 'medio', 'Quantas horas tem um dia?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/23f0.png', '["12", "18", "24", "30"]', 2),
(23, 'medio', 'Qual número vem depois de 99?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["98", "100", "101", "90"]', 1),
(24, 'medio', 'Qual instrumento tem teclas?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f3b9.png', '["Tambor", "Piano", "Violão", "Flauta"]', 1),
(25, 'medio', 'Qual é o dobro de 5?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["8", "9", "10", "11"]', 2),
(26, 'dificil', 'O que usamos para ouvir música?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f3a7.png', '["Colher", "Travesseiro", "Fone", "Caderno"]', 2),
(27, 'dificil', 'Qual é um meio de transporte?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f6b2.png', '["Bicicleta", "Almofada", "Lápis", "Bolo"]', 0),
(28, 'dificil', 'Se tem 10 balas e dá 3, fica com?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f36c.png', '["5", "6", "7", "8"]', 2),
(29, 'dificil', 'Qual planeta é vermelho?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1fa90.png', '["Marte", "Terra", "Júpiter", "Saturno"]', 0),
(30, 'dificil', 'Quanto é 6 x 4?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["20", "24", "28", "32"]', 1),
(31, 'dificil', 'Água sólida é chamada de?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/2744.png', '["Vapor", "Chuva", "Gelo", "Neve"]', 2),
(32, 'dificil', 'Qual gás as plantas liberam?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f33f.png', '["Oxigênio", "Fumaça", "Hélio", "Vapor"]', 0),
(33, 'dificil', 'Qual é o maior planeta?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1fa90.png', '["Marte", "Júpiter", "Terra", "Mercúrio"]', 1),
(34, 'dificil', 'Quantos lados tem hexágono?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f537.png', '["4", "5", "6", "8"]', 2),
(35, 'dificil', 'Qual órgão bombeia sangue?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/2764.png', '["Pulmão", "Cérebro", "Estômago", "Coração"]', 3),
(36, 'facil', 'Qual é a cor da grama?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f33f.png', '["Vermelho", "Azul", "Verde", "Amarelo"]', 2),
(37, 'facil', 'Quanto é 1 + 1?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["1", "2", "3", "4"]', 1),
(38, 'facil', 'Qual animal late?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f436.png', '["Gato", "Cachorro", "Pato", "Passarinho"]', 1),
(39, 'facil', 'Qual fruta é vermelha?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f353.png', '["Morango", "Banana", "Limão", "Coco"]', 0),
(40, 'facil', 'Quanto é 4 + 1?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["3", "4", "5", "6"]', 2),
(41, 'medio', 'Quantas rodas tem um carro?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f697.png', '["2", "3", "4", "5"]', 2),
(42, 'medio', 'Qual animal voa?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f985.png', '["Peixe", "Passarinho", "Leão", "Cachorro"]', 1),
(43, 'medio', 'Qual cor é o céu?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f30c.png', '["Verde", "Azul", "Vermelho", "Amarelo"]', 1),
(44, 'medio', 'Quantas patas tem um gato?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f431.png', '["2", "3", "4", "5"]', 2),
(45, 'medio', 'Qual é o dobro de 8?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["12", "14", "16", "18"]', 2),
(46, 'dificil', 'Quanto é 7 + 5?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["10", "11", "12", "13"]', 2),
(47, 'dificil', 'Qual é o resultado 8 x 3?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["20", "24", "28", "32"]', 1),
(48, 'dificil', 'Qual é 15 - 7?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["6", "7", "8", "9"]', 2),
(49, 'dificil', 'Qual é a metade de 20?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["8", "9", "10", "11"]', 2),
(50, 'dificil', 'Quanto é 12 ÷ 3?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["3", "4", "5", "6"]', 1),
(51, 'facil', 'Qual cor tem o tomate?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f345.png', '["Verde", "Amarelo", "Vermelho", "Roxo"]', 2),
(52, 'facil', 'Quantas orelhas tem um coelho?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f430.png', '["1", "2", "3", "4"]', 1),
(53, 'facil', 'Qual animal dá leite?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f404.png', '["Ovelha", "Vaca", "Cavalo", "Porco"]', 1),
(54, 'facil', 'Qual é a cor do mar?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f30a.png', '["Verde", "Azul", "Marrom", "Branco"]', 1),
(55, 'facil', 'Quanto é 8 + 2?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["8", "9", "10", "11"]', 2),
(56, 'medio', 'Qual animal tem chifres?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f410.png', '["Cachorro", "Cabra", "Gato", "Pato"]', 1),
(57, 'medio', 'Quanto é 3 x 3?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["6", "7", "8", "9"]', 3),
(58, 'medio', 'Qual forma é uma bola?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f4de.png', '["Quadrado", "Triângulo", "Esfera", "Retângulo"]', 2),
(59, 'medio', 'Quantos dedos tem uma mão?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f44b.png', '["3", "4", "5", "6"]', 2),
(60, 'dificil', 'Qual é 9 x 9?', 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f522.png', '["72", "81", "90", "99"]', 1)
ON CONFLICT (id) DO UPDATE SET nivel = EXCLUDED.nivel, pergunta = EXCLUDED.pergunta, imagem = EXCLUDED.imagem, opcoes = EXCLUDED.opcoes, resposta = EXCLUDED.resposta;